### PR TITLE
Adding some interview questions.

### PR DESCRIPTION
**Pull request by pranavsuryadevara**

### CODE REVIEW

**Comment by rutuja1121** [comment]
I  would like to work on this

**Comment by pranavsuryadevara** [comment]
Added LongestBitonic, LongestIncreasingSubsequences, MaxproductSubArray, MaxSumCircularArray.

**Comment by rutuja1121** [comment]
In which format should I send the questions?

**Comment by pranavsuryadevara** [comment]
Please consider merging them as my Hacktoberfest contribution.

**Pull request merged**
